apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: yourusername/userservice:1.0  # Replace with your actual Docker Hub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: NodePort  # Changed to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002  # Custom NodePort (optional, in range 30000-32767)
  selector:
    app: userservice
