apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: yourusername/productservice:1.0  # Replace with your actual Docker Hub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  type: NodePort  # Changed to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001  # Custom NodePort (optional, in range 30000-32767)
  selector:
    app: productservice
